### ISSUE TITLE
Index - Title and By Date list width

### ISSUE THREAD

**Issue by mopsal** [cpollett/Cinequest-iOS#35]
Hi Chris;
  Thank you again for the quick tweaks on the iPhone app. I think the biggest bug that needs to be fixed right now is cosmetic. The Index tab has two views, Title and By Date. Both of these views do not fill up the width of the window for the lists. For example, if you run the app in the iPhone 6 simulator you can see a bit of white space to the side of the list. It is more apparent with the iPhone 6 Plus simulator.

Is there a way to make it so the list views use the full width of the device that is currently using the app?

-matt

**Comment by cpollett** [comment]
Fixed by 6a73ad280e
