### ISSUE TITLE
Cover Image for iOS

### ISSUE THREAD

**Issue by mopsal** [cpollett/Cinequest-iOS#38]
Matt needs to provide the new Cover Image for the iOS "splash screen" what you see when you start the app.

I'll look for the dimensions or look at last years images and provide the image based on those dimensions.

-matt

**Comment by mopsal** [comment]
[iOS_SplashCoverImages_20160110.zip](https://github.com/cpollett/Cinequest-iOS/files/85175/iOS_SplashCoverImages_20160110.zip)

Chris, I found several iterations of the Cover "Splash" Image for iOS. Please let me know if any of the images in this .zip file are correct. Thanks!

-matt

**Comment by cpollett** [comment]
I just commited the code with the new images.
