### ISSUE TITLE
2014 Cover Image BUG

### ISSUE THREAD

**Issue by mopsal** [cpollett/Cinequest-iOS#39]
Chris, this is for the 2014 cover image bug that I was describing this morning. I already have the app installed on my iPhone 6, and for a brief moment I see the 2014 Cover Image (black with red, blue and yellow dots, text says "connect") before I see the 2015 Cover Image (women jumping with burning wings) and the app starts. This may be something that everyone sees (you said you don't see it), or only people that have previously installed the app see (me).

-matt

**Comment by cpollett** [comment]
Fixed with 86a27c52a02
